services:
  - type: web
    name: youtube-to-mp3-converter
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 3000
    buildFilter:
      paths:
      - app.js
      - package.json
    disk:
      name: cache
      mountPath: /cache
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true
    plan: free